version: '3'

services:
  express:
    build: ./backend/dockerfile
    container_name: express-container
    hostname: express-server
    tty: true
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=3001
    volumes:
      - ./backend:/usr/src/app
      - express-data:/usr/src/aoo/node_modules
    ports:
      - 3001:3001
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn global add nodemon && nodemon app.js"

  react:
    build: ./frontend/dockerfile
    container_name: react-container
    hostname: react-server
    tty: true
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=3000
    volumes:
      - ./frontend/:/usr/src/app
      - react-data:/usr/src/app/node_modules
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn start"

  mysql:
    build: ./db/mysql/dockerfile
    container_name: mysql-container
    hostname: mysql-server
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Japan
    volumes:
      - mysql-data:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - 3306:3306
    restart: always

volumes:
  mysql-data:
    name: db-data
  express-data:
    name: express-data
  react-data:
    name: react-data
